services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        TZ: ${TZ:-America/Los_Angeles}
    container_name: gtfs-delay-prediction-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ..:/app:cached
    working_dir: /app
    networks:
      - devcontainer-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: gtfs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/vencoucer-bus-scienmce
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  postgres:
    image: postgres:17.4-alpine3.21
    container_name: gtfs-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - gtfs_devcontainer_postgres-data:/var/lib/postgresql/data
    networks:
      - devcontainer-network

networks:
  devcontainer-network:
    driver: bridge

volumes:
  gtfs_devcontainer_postgres-data:
    external: true